---
title: 'Class 04: Data structures and data import'
author: "Nick Begany"
date: "2026-09-02"
output: 
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    code_downloading: true 
    code_folding: show
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

crashes_by_day = c(2020, 2241, 2327, 2285, 2380, 1866, 1664)
names(crashes_by_day) = c("Mon", "Tue", "Wed", "Thu",
                          "Fri", "Sat", "Sun")

crashes_df = tibble::tibble(
  day     = names(crashes_by_day),
  crashes = crashes_by_day,
  busy    = crashes_by_day > 2000)

crashes_df$crashes

dplyr::glimpse(crashes_df) 
```

```{r}
example_list = list(
  1:3,                    # integers 1, 2, 3
  "a",                    # one piece of text
  c(TRUE, FALSE, TRUE),   # three logicals
  c(2.3, 5.9)             # two decimals
)
str(example_list)         # the x-ray view
```

```{r}
str(example_list[1]) 
```

```{r}
job = list(
  title   = "Research Data Scientist, Magic Eye",
  company = "Google",
  salary  = list(min = 147000, max = 210000)
)
str(job)
```
1. The company name 
```{r company_name}
company_name = job$company
print(company_name)

company_name_as_names_list = job[2]
```

2. The maximum salary
```{r}
max_salary = job$salary$max
```

3. Max salary again, using only [[]]
```{r}
job[[3]][[2]]
```

4. The names of elements in job
```{r}
names(job)
```

# Subsection 

## Vectors

- You can subset by position (i.e., a number) or by name if it is a named vector;
- You can also pass a vector (e.g., logical condition 2:4 or c( ) ) for subsetting the vector 

```{r}
crashes_by_day = c(2020, 2241, 2327, 2285, 2380, 1866, 1664)
names(crashes_by_day) = c("Mon", "Tue", "Wed", "Thu",
                          "Fri", "Sat", "Sun")
crashes_by_day[2:4]
crashes_by_day[c('Mon', 'Fri')]
```


```{r}
crashes_df = tibble::tibble(
  day     = names(crashes_by_day),
  crashes = crashes_by_day,
  busy    = crashes_by_day > 2000)
crashes_df$crashes                     # one column, as a vector
```

```{r}
crashes_df[["crashes"]]                # the same vector, by name
```

```{r}
crashes_df[1:2, c("day", "crashes")]   # rows 1 to 2, two columns
```



# Ohio Jobs
```{r}
oh_jobs = readr::read_csv(
  file = "https://fred.stlouisfed.org/graph/fredgraph.csv?bgcolor=%23ebf3fb&chart_type=line&drp=0&fo=open%20sans&graph_bgcolor=%23ffffff&height=450&mode=fred&recession_bars=on&txtcolor=%23444444&ts=12&tts=12&width=1320&nt=0&thu=0&trc=0&show_legend=yes&show_axis_titles=yes&show_tooltip=yes&id=IHLIDXUSOH&scale=left&cosd=2021-08-28&coed=2026-08-28&line_color=%230073e6&link_values=false&line_style=solid&mark_type=none&mw=3&lw=3&ost=-99999&oet=99999&mma=0&fml=a&fq=Daily%2C%207-Day&fam=avg&fgst=lin&fgsnd=2020-02-01&line_index=1&transformation=lin&vintage_date=2026-09-02&revision_date=2026-09-02&nd=2020-02-01"
)
```
```{r}
dplyr::glimpse(oh_jobs)
```

```{r}
oh_jobs_base_r = read.csv(
  file = "https://fred.stlouisfed.org/graph/fredgraph.csv?bgcolor=%23ebf3fb&chart_type=line&drp=0&fo=open%20sans&graph_bgcolor=%23ffffff&height=450&mode=fred&recession_bars=on&txtcolor=%23444444&ts=12&tts=12&width=1320&nt=0&thu=0&trc=0&show_legend=yes&show_axis_titles=yes&show_tooltip=yes&id=IHLIDXUSOH&scale=left&cosd=2021-08-28&coed=2026-08-28&line_color=%230073e6&link_values=false&line_style=solid&mark_type=none&mw=3&lw=3&ost=-99999&oet=99999&mma=0&fml=a&fq=Daily%2C%207-Day&fam=avg&fgst=lin&fgsnd=2020-02-01&line_index=1&transformation=lin&vintage_date=2026-09-02&revision_date=2026-09-02&nd=2020-02-01"
)
```

```{r}
dplyr::glimpse(oh_jobs_base_r)
```

```{r}
z = 4+7
print(z)
```

