---
title: "In Class 12"
author: "Nick Begany"
date: "2026-10-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## continuing scraping data from the website planecrashinfo

The website that we want to scrape is called: <https://www.planecrashinfo.com/> and it contains a database of plane crashes by year.

```{r}
year = 2025

crash_url = paste0('https://www.planecrashinfo.com/', year, '/', year, '.htm')

crash_page = rvest::read_html(crash_url, encoding = "ISA-8859-1")

crash_page

crash_tables <- crash_page |>
  rvest::html_elements("table") |>
  rvest::html_table()

# from a cleaning perspective: 
# [1] translate this into a DF instead of a list
# [2] replace the current headers with row 1 and then delete row 1
# [3] convert date into a date column instead of chr 
# [4] more complex cleaning to split multiple information within a cell into separate columns

# back to our pepper shaker analogy 
crash_df = crash_tables[[1]] # subsetting a list 

colnames(crash_df) = crash_df[1, ] 
crash_df = crash_df[-1, ]

# convert date column into a date type obj
crash_df = crash_df |>
  dplyr::mutate(Date = lubridate::dmy(Date))

dplyr::glimpse(crash_df)
```


# In-class game

```{r}
page = rvest::read_html("https://isa401-salvage.vercel.app/registry?start=1")
classes = page |>
  rvest::html_elements(".Dreadnought") |>
  rvest::html_text2()
length(classes)   # check this first: one per card
```

```{r}
base = "https://isa401-salvage.vercel.app"
starts = seq(from = 1, to = 351, by = 50)
pages = vector("list", length(starts))
for (i in seq_along(starts)) {
  pg = rvest::read_html(paste0(base, "/registry?start=", starts[i]))
  pages[[i]] = data.frame(
    class = pg |> rvest::html_element("div > ul > li:nth-child(1) > span") |>
      rvest::html_text2(),
    value = pg |> rvest::html_element("div > ul > li:nth-child(3) > span") |>
      rvest::html_text2() |> readr::parse_number()
  )
  Sys.sleep(1)   # robots.txt asks for it
}
registry = dplyr::bind_rows(pages)   # 400 rows?

dreadnought_df = registry |> 
  dplyr::filter(class == "Dreadnought")

sum(dreadnought_df$value)
```


